"""CI/CD, autonomous loop, cron scheduling, and workspace commands."""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import textwrap
import uuid
from pathlib import Path
from typing import Any

from tag.core.config import load_config, config_path
from tag.core.db import open_db, queue_update_pid, launch_queue_worker
from tag.core.paths import (
    hermes_bin,
    hermes_root,
    runtime_db_path,
    profile_exec_env,
    ensure_runtime_dirs,
)
from tag.core.utils import utc_now, nonnegative_int

try:
    from tag.tui_output import print_error, print_success, print_warning
except Exception:
    def print_error(msg): print(f"error: {msg}", file=sys.stderr)
    def print_success(msg): print(msg)
    def print_warning(msg): print(f"warning: {msg}", file=sys.stderr)


def _master_profile(cfg: dict[str, Any]) -> str:
    """Resolve the default master profile with one consistent, defensive lookup.

    Some configs nest it under ``defaults.master_profile`` and some put it at the
    top level; a minimal config may have neither. Previously loop/cron used an
    unguarded ``cfg['defaults']['master_profile']`` (KeyError on a minimal
    config) while review-pr/ci used ``cfg.get('master_profile', ...)`` — this
    unifies both paths.
    """
    return (
        (cfg.get("defaults") or {}).get("master_profile")
        or cfg.get("master_profile")
        or "orchestrator"
    )


def _emit_error(args: argparse.Namespace, msg: str, code: int = 1) -> int:
    """Emit an error respecting ``--json``: valid JSON when requested, else plain."""
    if getattr(args, "json", False):
        print(json.dumps({"error": msg}))
    else:
        print_error(msg)
    return code


# ---------------------------------------------------------------------------
# PRD-020: review-pr
# ---------------------------------------------------------------------------

def cmd_review_pr(args: argparse.Namespace) -> int:
    cfg = load_config(config_path(getattr(args, "config", None)))
    repo = getattr(args, "repo", None)
    pr_number = getattr(args, "pr", None)
    profile = getattr(args, "profile", None) or _master_profile(cfg)
    post_comments = getattr(args, "post_comments", False)

    try:
        from tag.ci import (
            fetch_pr_diff,
            fetch_pr_metadata,
            post_pr_comment,
            build_review_prompt,
        )
    except ImportError as exc:
        print_error(f"tag.ci not available: {exc}")
        return 1

    if not repo or not pr_number:
        print_error("Provide --repo owner/name and --pr NUMBER")
        return 1

    print(f"Fetching PR #{pr_number} from {repo}...")
    try:
        diff = fetch_pr_diff(repo, pr_number)
        metadata = fetch_pr_metadata(repo, pr_number)
    except (RuntimeError, ValueError) as exc:
        print_error(str(exc))
        return 1

    prompt_text = build_review_prompt(diff, metadata)

    print(f"Running code review with profile '{profile}'...")
    result = subprocess.run(
        [str(hermes_bin(cfg)), "chat", "-q", prompt_text, "-Q"],
        env=profile_exec_env(cfg, profile),
        capture_output=True, text=True,
    )
    review_text = result.stdout.strip()

    if not review_text:
        print_error("No review output received from agent")
        return 1

    if post_comments:
        body = f"## TAG Automated Code Review\n\n{review_text}\n\n---\n*Generated by tag-agent*"
        ok = post_pr_comment(repo, pr_number, body)
        if ok:
            print_success(f"Posted review comment to {repo}#{pr_number}")
        else:
            print_warning("Failed to post comment — printing review instead:")
            print(review_text)
    else:
        print(review_text)

    return 0


# ---------------------------------------------------------------------------
# PRD-020: ci
# ---------------------------------------------------------------------------

def cmd_ci(args: argparse.Namespace) -> int:
    cfg = load_config(config_path(getattr(args, "config", None)))
    sub = getattr(args, "ci_subcommand", None)
    profile = getattr(args, "profile", None) or _master_profile(cfg)

    try:
        from tag.ci import (
            build_diagnose_prompt,
            read_ci_log,
            detect_git_host,
            get_staged_diff,
        )
    except ImportError as exc:
        print_error(f"tag.ci not available: {exc}")
        return 1

    if sub == "diagnose":
        log_path = getattr(args, "log_file", None)
        if not log_path:
            print_error("Provide --log-file PATH")
            return 1
        try:
            log_content = read_ci_log(Path(log_path))
        except FileNotFoundError:
            print_error(f"Log file not found: {log_path}")
            return 1
        prompt_text = build_diagnose_prompt(log_content)
        result = subprocess.run(
            [str(hermes_bin(cfg)), "chat", "-q", prompt_text, "-Q"],
            env=profile_exec_env(cfg, profile),
            capture_output=True, text=True,
        )
        print(result.stdout.strip() or "(no output)")
        return result.returncode

    if sub == "commit-lint":
        diff = get_staged_diff()
        if not diff.strip():
            print("No staged changes. Stage your changes with `git add` first.")
            return 1
        prompt_text = textwrap.dedent(f"""\
            Review the following staged git diff and suggest a concise conventional commit message.
            Format: <type>(<scope>): <subject>
            Types: feat, fix, docs, style, refactor, perf, test, chore
            Keep subject under 72 characters.

            Diff:
            {diff[:4000]}
        """)
        result = subprocess.run(
            [str(hermes_bin(cfg)), "chat", "-q", prompt_text, "-Q"],
            env=profile_exec_env(cfg, profile),
            capture_output=True, text=True,
        )
        print(result.stdout.strip() or "(no output)")
        return result.returncode

    if sub == "status":
        host = detect_git_host()
        print(f"Git host: {host}")
        result = subprocess.run(["git", "status", "--short"], capture_output=True, text=True)
        print(result.stdout or "(clean)")
        return 0

    print_error(f"Unknown subcommand: {sub}")
    return 1


# ---------------------------------------------------------------------------
# PRD-021: Agent Loop / Autonomous Mode
# ---------------------------------------------------------------------------

def _launch_loop_worker(cfg: dict[str, Any], loop_id: str) -> int:
    """Spawn loop_agent as a detached background process. Returns PID."""
    db_path = runtime_db_path(cfg)
    proc = subprocess.Popen(
        [sys.executable, "-m", "tag.loop_agent",
         "--loop-id", loop_id,
         "--config", str(config_path(None)),
         "--db", str(db_path)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    return proc.pid


def cmd_loop(args: argparse.Namespace) -> int:
    """PRD-021: Autonomous agent loop with iteration cap and goal detection."""
    cfg = load_config(config_path(getattr(args, "config", None)))
    ensure_runtime_dirs(cfg)
    db = open_db(cfg)
    sub = getattr(args, "loop_subcommand", "list")

    if sub == "start":
        goal = (getattr(args, "goal", "") or "").strip()
        if not goal:
            db.close()
            return _emit_error(args, "--goal TEXT is required")
        profile = getattr(args, "profile", None) or _master_profile(cfg)
        max_iters = getattr(args, "max_iters", 10)
        if max_iters is None:
            max_iters = 10
        if max_iters < 1:
            db.close()
            return _emit_error(args, "--max-iters must be >= 1")
        approval = getattr(args, "approval", "auto") or "auto"
        if approval not in ("auto", "human"):
            db.close()
            return _emit_error(args, "--approval must be 'auto' or 'human'")

        loop_id = uuid.uuid4().hex[:12]
        now = utc_now()
        db.execute(
            """INSERT INTO loop_runs(id, profile, goal, max_iters, current_iter,
               status, approval, created_at, updated_at)
               VALUES(?,?,?,?,0,'running',?,?,?)""",
            (loop_id, profile, goal, max_iters, approval, now, now),
        )
        db.commit()

        pid = _launch_loop_worker(cfg, loop_id)
        db.close()

        if getattr(args, "json", False):
            print(json.dumps({"loop_id": loop_id, "pid": pid, "status": "running"}))
        else:
            print(f"loop started: {loop_id}  (worker pid {pid})")
            print(f"goal: {goal[:80]}")
            print(f"max iterations: {max_iters}  approval: {approval}")
        return 0

    if sub == "list":
        rows = db.execute(
            "SELECT id, profile, status, current_iter, max_iters, created_at, goal "
            "FROM loop_runs ORDER BY created_at DESC LIMIT 20"
        ).fetchall()
        db.close()
        if getattr(args, "json", False):
            print(json.dumps([dict(r) for r in rows], indent=2))
            return 0
        if not rows:
            print("No loop runs.")
            return 0
        print(f"  {'ID':<14} {'PROFILE':<16} {'STATUS':<12} {'ITERS':<8} {'GOAL'}")
        print("  " + "─" * 76)
        for r in rows:
            goal_short = (r["goal"] or "")[:40]
            iters = f"{r['current_iter']}/{r['max_iters']}"
            print(f"  {r['id']:<14} {r['profile']:<16} {r['status']:<12} {iters:<8} {goal_short}")
        return 0

    if sub == "status":
        loop_id = getattr(args, "loop_id", None)
        if not loop_id:
            db.close()
            return _emit_error(args, "LOOP_ID required")
        run = db.execute("SELECT * FROM loop_runs WHERE id=?", (loop_id,)).fetchone()
        if not run:
            db.close()
            return _emit_error(args, f"Loop '{loop_id}' not found")
        iters = db.execute(
            "SELECT iteration, decision, output FROM loop_iterations WHERE loop_id=? ORDER BY iteration",
            (loop_id,),
        ).fetchall()
        db.close()
        run_d = dict(run)
        if getattr(args, "json", False):
            run_d["iterations"] = [dict(i) for i in iters]
            print(json.dumps(run_d, indent=2))
            return 0
        print(f"Loop: {loop_id}")
        print(f"  Profile: {run_d['profile']}  Status: {run_d['status']}")
        print(f"  Goal: {run_d['goal'][:80]}")
        print(f"  Iterations: {run_d['current_iter']}/{run_d['max_iters']}")
        for it in iters:
            print(f"  [{it['iteration']}] {it['decision']}: {(it['output'] or '')[:80]}")
        return 0

    if sub == "abort":
        loop_id = getattr(args, "loop_id", None)
        if not loop_id:
            db.close()
            return _emit_error(args, "LOOP_ID required")
        cur = db.execute(
            "UPDATE loop_runs SET status='aborted', updated_at=? WHERE id=? AND status='running'",
            (utc_now(), loop_id),
        )
        db.commit()
        affected = cur.rowcount
        db.close()
        if affected == 0:
            return _emit_error(args, f"No running loop found: {loop_id}")
        print(f"abort requested: {loop_id}")
        return 0

    if sub in ("approve", "deny"):
        loop_id = getattr(args, "loop_id", None)
        db.close()
        if not loop_id:
            return _emit_error(args, "LOOP_ID required")
        # Producer for the human-approval gate that loop_agent._request_approval
        # polls: write the decision into loop-approvals/<id>.json next to the DB.
        # The worker reads data["decision"] and treats "continue" as approve and
        # "abort" as deny — match that exact contract (B021).
        decision = "continue" if sub == "approve" else "abort"
        approval_file = runtime_db_path(cfg).parent / "loop-approvals" / f"{loop_id}.json"
        if not approval_file.exists():
            return _emit_error(
                args,
                f"No pending approval request for loop '{loop_id}'. The loop must be "
                "running with --approval human and waiting at a checkpoint.",
            )
        try:
            data = json.loads(approval_file.read_text())
        except (OSError, ValueError):
            data = {"loop_id": loop_id}
        data["decision"] = decision
        approval_file.write_text(json.dumps(data))
        if getattr(args, "json", False):
            print(json.dumps({"loop_id": loop_id, "decision": decision}))
        else:
            verb = "approved (continue)" if sub == "approve" else "denied (abort)"
            print(f"loop {loop_id} {verb}")
        return 0

    db.close()
    return 0


# ---------------------------------------------------------------------------
# PRD-022: Cron / Scheduled Agents
# ---------------------------------------------------------------------------

def cmd_cron(args: argparse.Namespace) -> int:
    """PRD-022: Cron-style scheduled agent runs."""
    cfg = load_config(config_path(getattr(args, "config", None)))
    ensure_runtime_dirs(cfg)
    db = open_db(cfg)
    sub = getattr(args, "cron_subcommand", "list")

    if sub == "add":
        from tag.cron_scheduler import validate_cron_expression
        name = (getattr(args, "name", "") or "").strip()
        schedule = (getattr(args, "schedule", "") or "").strip()
        profile = getattr(args, "profile", None) or _master_profile(cfg)
        task = (getattr(args, "task", "") or "").strip()
        if not name or not schedule or not task:
            db.close()
            return _emit_error(args, "--name, --schedule and TASK are required")
        try:
            validate_cron_expression(schedule)
        except ValueError as exc:
            db.close()
            return _emit_error(args, str(exc))
        existing = db.execute("SELECT id FROM cron_jobs WHERE name=?", (name,)).fetchone()
        if existing:
            db.close()
            return _emit_error(args, f"A cron job named '{name}' already exists (names must be unique)")
        job_id = uuid.uuid4().hex[:8]
        now = utc_now()
        db.execute(
            """INSERT INTO cron_jobs(id, name, schedule, profile, task, enabled,
               run_count, created_at, updated_at)
               VALUES(?,?,?,?,?,1,0,?,?)""",
            (job_id, name, schedule, profile, task, now, now),
        )
        db.commit()
        db.close()
        if getattr(args, "json", False):
            print(json.dumps({"id": job_id, "name": name, "schedule": schedule}))
        else:
            print(f"cron job added: {job_id}  '{name}'  [{schedule}]")
        return 0

    if sub == "list":
        rows = db.execute(
            "SELECT id, name, schedule, profile, enabled, last_run_at, run_count FROM cron_jobs ORDER BY name"
        ).fetchall()
        db.close()
        if getattr(args, "json", False):
            print(json.dumps([dict(r) for r in rows], indent=2))
            return 0
        if not rows:
            print("No cron jobs.")
            return 0
        print(f"  {'ID':<10} {'NAME':<20} {'SCHEDULE':<16} {'PROFILE':<14} {'EN':<4} {'RUNS':>5} {'LAST RUN'}")
        print("  " + "─" * 80)
        for r in rows:
            en = "✓" if r["enabled"] else "✗"
            last = (r["last_run_at"] or "never")[:19]
            print(f"  {r['id']:<10} {r['name']:<20} {r['schedule']:<16} {r['profile']:<14} {en:<4} {r['run_count']:>5} {last}")
        return 0

    if sub == "remove":
        job_id = getattr(args, "job_id", None)
        if not job_id:
            db.close()
            return _emit_error(args, "JOB_ID required")
        cur = db.execute("DELETE FROM cron_jobs WHERE id=?", (job_id,))
        db.commit()
        db.close()
        if cur.rowcount == 0:
            return _emit_error(args, f"Job '{job_id}' not found")
        print(f"removed: {job_id}")
        return 0

    if sub in ("enable", "disable"):
        job_id = getattr(args, "job_id", None)
        if not job_id:
            db.close()
            return _emit_error(args, "JOB_ID required")
        enabled = 1 if sub == "enable" else 0
        cur = db.execute(
            "UPDATE cron_jobs SET enabled=?, updated_at=? WHERE id=?",
            (enabled, utc_now(), job_id),
        )
        db.commit()
        db.close()
        if cur.rowcount == 0:
            return _emit_error(args, f"Job '{job_id}' not found")
        print(f"{sub}d: {job_id}")
        return 0

    if sub == "run":
        # Trigger a cron job immediately (one-shot, ignores schedule)
        job_id = getattr(args, "job_id", None)
        if not job_id:
            db.close()
            return _emit_error(args, "JOB_ID required")
        job = db.execute("SELECT * FROM cron_jobs WHERE id=?", (job_id,)).fetchone()
        if not job:
            db.close()
            return _emit_error(args, f"Job '{job_id}' not found")
        q_id = uuid.uuid4().hex[:8]
        now = utc_now()
        db.execute(
            """INSERT INTO queue_jobs(id, profile, task, task_type, status, priority, created_at, notify)
               VALUES(?,?,?,?,?,?,?,?)""",
            (q_id, job["profile"], job["task"], "mixed", "queued", 5, now, 1),
        )
        db.execute(
            "UPDATE cron_jobs SET last_run_at=?, run_count=run_count+1, updated_at=? WHERE id=?",
            (now, now, job_id),
        )
        db.commit()
        pid = launch_queue_worker(cfg, q_id)
        queue_update_pid(db, q_id, pid)
        db.commit()
        db.close()
        print(f"triggered: cron job {job_id} → queue job {q_id} (pid {pid})")
        return 0

    if sub == "daemon":
        # Run the cron daemon in-process (blocking)
        db.close()
        from tag.cron_scheduler import run_daemon
        db_path = str(runtime_db_path(cfg))
        cfg_path = str(config_path(getattr(args, "config", None)) or "")
        print(f"TAG cron daemon starting (polling every 30s) — Ctrl+C to stop")
        try:
            run_daemon(db_path, cfg_path)
        except KeyboardInterrupt:
            print("\ncron daemon stopped.")
        return 0

    db.close()
    return 0


# ---------------------------------------------------------------------------
# PRD-024: Repo-Map / Workspace Context
# ---------------------------------------------------------------------------

def cmd_workspace(args: argparse.Namespace) -> int:
    """PRD-024: Workspace file indexing and token-efficient repo-map generation."""
    cfg = load_config(config_path(getattr(args, "config", None)))
    ensure_runtime_dirs(cfg)
    db = open_db(cfg)
    sub = getattr(args, "workspace_subcommand", "status")

    try:
        from tag.workspace import index_workspace, build_workspace_map, workspace_status
    except ImportError as exc:
        db.close()
        print_error(f"tag.workspace not available: {exc}")
        return 1

    root = Path(getattr(args, "path", None) or ".").resolve()

    if sub == "index":
        if not root.is_dir():
            db.close()
            return _emit_error(args, f"Not a directory: {root}")
        max_files = getattr(args, "max_files", None)
        if max_files is None:
            max_files = 500
        try:
            result = index_workspace(db, root, max_files=max_files)
        except ValueError as exc:
            # e.g. --max-files 0: close the connection on this error path too
            # (previously the raise skipped db.close(), leaking the connection).
            db.close()
            return _emit_error(args, str(exc))
        db.close()
        if getattr(args, "json", False):
            print(json.dumps(result))
        else:
            print(f"Indexed {result['files_indexed']} files ({result['total_tokens']} tokens)")
            if result["max_rank_file"]:
                print(f"Top-ranked file: {result['max_rank_file']}")
        return 0

    if sub == "map":
        budget = getattr(args, "budget", 4000)
        if budget is None:
            budget = 4000
        ws_map = build_workspace_map(db, root, budget_tokens=budget)
        db.close()
        if getattr(args, "json", False):
            print(json.dumps({"map": ws_map}))
        else:
            print(ws_map)
        return 0

    if sub == "status":
        stats = workspace_status(db)
        db.close()
        if getattr(args, "json", False):
            print(json.dumps(stats))
        else:
            if stats["file_count"] == 0:
                print("Workspace not indexed. Run `tag workspace index` first.")
            else:
                print(f"Indexed: {stats['file_count']} files  {stats['total_tokens']} tokens")
                print(f"Last indexed: {stats['last_indexed'] or 'never'}")
        return 0

    if sub == "clear":
        db.execute("DELETE FROM workspace_files")
        db.commit()
        db.close()
        print("Workspace index cleared.")
        return 0

    db.close()
    return 0


# ---------------------------------------------------------------------------
# Parser registration
# ---------------------------------------------------------------------------

def register(sub: argparse._SubParsersAction) -> None:  # type: ignore[type-arg]
    """Register review-pr, ci, loop, cron, and workspace subcommands."""

    # ---- PRD-020: review-pr / ci ----
    review_pr_cmd = sub.add_parser("review-pr", help="AI code review for a GitHub pull request")
    review_pr_cmd.add_argument("--repo", required=True, help="GitHub repository (owner/name)")
    review_pr_cmd.add_argument("--pr", required=True, type=int, metavar="NUMBER")
    review_pr_cmd.add_argument("--profile", help="Profile to run review with")
    review_pr_cmd.add_argument("--post-comments", action="store_true", dest="post_comments",
                               help="Post review as a PR comment via gh CLI")
    review_pr_cmd.set_defaults(func=cmd_review_pr)

    ci_cmd = sub.add_parser("ci", help="CI/CD integration utilities")
    ci_sub = ci_cmd.add_subparsers(dest="ci_subcommand")
    ci_diagnose = ci_sub.add_parser("diagnose", help="Diagnose a CI failure from a log file")
    ci_diagnose.add_argument("--log-file", required=True, dest="log_file", metavar="PATH")
    ci_diagnose.add_argument("--profile")
    ci_lint = ci_sub.add_parser("commit-lint", help="Suggest a conventional commit message for staged changes")
    ci_lint.add_argument("--profile")
    ci_status = ci_sub.add_parser("status", help="Show git host and working tree status")
    for cp in [ci_cmd, ci_diagnose, ci_lint, ci_status]:
        cp.set_defaults(func=cmd_ci)

    # ---- PRD-021: loop ----
    loop_cmd = sub.add_parser("loop", help="Autonomous agent loop with goal detection and iteration cap")
    loop_sub = loop_cmd.add_subparsers(dest="loop_subcommand")
    loop_start = loop_sub.add_parser("start", help="Start an autonomous loop")
    loop_start.add_argument("--goal", required=True, help="Goal text the loop works toward")
    loop_start.add_argument("--profile", help="Profile to run (default: orchestrator)")
    loop_start.add_argument("--max-iters", type=int, default=10, dest="max_iters",
                            help="Maximum number of iterations (default: 10)")
    loop_start.add_argument("--approval", choices=["auto", "human"], default="auto",
                            help="Gate mode: auto continues automatically, human pauses for approval")
    loop_start.add_argument("--json", action="store_true")
    loop_list = loop_sub.add_parser("list", help="List all loop runs")
    loop_list.add_argument("--json", action="store_true")
    loop_status_p = loop_sub.add_parser("status", help="Show status and iterations of a loop")
    loop_status_p.add_argument("loop_id", metavar="LOOP_ID")
    loop_status_p.add_argument("--json", action="store_true")
    loop_abort = loop_sub.add_parser("abort", help="Abort a running loop")
    loop_abort.add_argument("loop_id", metavar="LOOP_ID")
    loop_approve = loop_sub.add_parser("approve", help="Approve a loop waiting for human approval (continue)")
    loop_approve.add_argument("loop_id", metavar="LOOP_ID")
    loop_approve.add_argument("--json", action="store_true")
    loop_deny = loop_sub.add_parser("deny", help="Deny a loop waiting for human approval (abort)")
    loop_deny.add_argument("loop_id", metavar="LOOP_ID")
    loop_deny.add_argument("--json", action="store_true")
    for lp in [loop_cmd, loop_start, loop_list, loop_status_p, loop_abort, loop_approve, loop_deny]:
        lp.set_defaults(func=cmd_loop)

    # ---- PRD-022: cron ----
    cron_cmd = sub.add_parser("cron", help="Cron-style scheduled agent runs")
    cron_sub = cron_cmd.add_subparsers(dest="cron_subcommand")
    cron_add = cron_sub.add_parser("add", help="Add a cron job")
    cron_add.add_argument("--name", required=True, help="Unique job name")
    cron_add.add_argument("--schedule", required=True, help="5-field cron expression (e.g. '0 9 * * 1-5')")
    cron_add.add_argument("--profile", help="Profile to run task with")
    cron_add.add_argument("task", metavar="TASK", help="Task text to submit")
    cron_add.add_argument("--json", action="store_true")
    cron_list = cron_sub.add_parser("list", help="List all cron jobs")
    cron_list.add_argument("--json", action="store_true")
    cron_remove = cron_sub.add_parser("remove", help="Remove a cron job")
    cron_remove.add_argument("job_id", metavar="JOB_ID")
    cron_enable = cron_sub.add_parser("enable", help="Enable a cron job")
    cron_enable.add_argument("job_id", metavar="JOB_ID")
    cron_disable = cron_sub.add_parser("disable", help="Disable a cron job")
    cron_disable.add_argument("job_id", metavar="JOB_ID")
    cron_run = cron_sub.add_parser("run", help="Trigger a cron job immediately (ignore schedule)")
    cron_run.add_argument("job_id", metavar="JOB_ID")
    cron_daemon = cron_sub.add_parser("daemon", help="Run the cron daemon in-process (blocking)")
    for cp in [cron_cmd, cron_add, cron_list, cron_remove, cron_enable, cron_disable, cron_run, cron_daemon]:
        cp.set_defaults(func=cmd_cron)

    # ---- PRD-024: workspace ----
    ws_cmd = sub.add_parser("workspace", help="Repo-map and workspace context indexing")
    ws_sub = ws_cmd.add_subparsers(dest="workspace_subcommand")
    ws_index = ws_sub.add_parser("index", help="Index workspace files")
    ws_index.add_argument("--path", default=".", help="Root path to index (default: .)")
    ws_index.add_argument("--max-files", type=int, default=500, dest="max_files")
    ws_index.add_argument("--json", action="store_true")
    ws_map = ws_sub.add_parser("map", help="Print token-efficient workspace map")
    ws_map.add_argument("--path", default=".", help="Root path")
    ws_map.add_argument("--budget", type=int, default=4000, help="Token budget (default: 4000)")
    ws_map.add_argument("--json", action="store_true")
    ws_status = ws_sub.add_parser("status", help="Show workspace index statistics")
    ws_status.add_argument("--json", action="store_true")
    ws_clear = ws_sub.add_parser("clear", help="Clear workspace index")
    for wp in [ws_cmd, ws_index, ws_map, ws_status, ws_clear]:
        wp.set_defaults(func=cmd_workspace)
